#include "../include/syscall.h"
#include "../include/memory.h"
SYSCALL(mmap, sys_mmap);
SYSCALL(munmap, sys_munmap);
SYSCALL(mprotect, sys_mprotect);
SYSCALL(msync, sys_msync);
SYSCALL(mlock, sys_mlock);
SYSCALL(munlock, sys_munlock);
SYSCALL(getMemoryInfo, sys_query_memory_protection);
SYSCALL(getOtherMemoryInfo, sys_virtual_query);
